---
- hosts: all
  vars:
    go_version: 1.5.3
  sudo: yes
  tasks:

    - name: Remove unneeded Packages
      apt: name={{item}} state=absent purge=yes
      with_items:
        - chef
        - puppet
        - exim4
        - exim4-base
        - exim4-config
        - exim4-daemon-light

    - name: Update APT cache and upgrade all packages
      apt: update_cache=yes force=yes

    - name: Install apt-transport-https
      apt: name=apt-transport-https state=latest force=yes install_recommends=no

    - name: Add docker gpg key
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

    - name: Add docker source.list
      lineinfile: dest=/etc/apt/sources.list.d/docker.list create=yes line="deb https://apt.dockerproject.org/repo debian-jessie main"

    - name: Install requirements
      apt: name={{item}} state=latest force=yes install_recommends=no
      with_items:
        - git
        - docker-engine

    - name: Download golang
      get_url: url=https://storage.googleapis.com/golang/go{{go_version}}.linux-amd64.tar.gz dest=/tmp

    - name: Untar golang
      unarchive: src=/tmp/go{{go_version}}.linux-amd64.tar.gz dest=/usr/local

    - name: Add go to $PATH
      lineinfile: dest=/etc/profile line="export PATH=$PATH:/usr/local/go/bin"

    #- name: Start docker service
    #  service: name=docker state=started

    #- name: Start mongodb container
    #  docker:
    #    name: bookmark-mongodb
    #    image: mongo
    #    state: running
    #    ports:
    #      - "27017:27017"
